[project]
name = "odoo-addons-oca-crm"
version = "18.0.20250331.0"
dependencies = [
    "odoo-addon-crm_lead_code==18.0.*",
    "odoo-addon-crm_lead_firstname==18.0.*",
    "odoo-addon-crm_phonecall==18.0.*",
    "odoo-addon-crm_stage_probability==18.0.*",
    "odoo-addon-crm_won_restrict_per_stage==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
